version: '3.8'

services:
  # Backend API service
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "5002:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_EXPIRE=30d
      - DB_DIALECT=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=ethical_hacking_lms
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    volumes:
      - ./data:/app/data
    depends_on:
      - postgres
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile.simple
    ports:
      - "8080:80"
    environment:
      - API_URL=http://backend:5001
    depends_on:
      - backend
    restart: unless-stopped

  # PostgreSQL database
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ethical_hacking_lms
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
