version: '3.8'

services:
  # Backend API service
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "5002:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_EXPIRE=30d
      - DB_DIALECT=sqlite
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - API_URL=http://backend:5001
    depends_on:
      - backend
    restart: unless-stopped
