services:
  # Backend API service
  - type: web
    name: ethical-hacking-lms-api
    env: node
    region: oregon
    plan: free
    buildCommand: cd src/backend && npm install
    startCommand: cd src/backend && node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 30d
      - key: DB_DIALECT
        value: sqlite

  # Frontend static site
  - type: web
    name: ethical-hacking-lms
    env: static
    # Removed region as static sites cannot have a region
    plan: free
    buildCommand: cd src/frontend && npm install && npm run build
    staticPublishPath: ./src/frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          name: ethical-hacking-lms-api
          type: web
          property: host # Changed from url to host
        suffix: /api
