services:
  # Backend API service
  - type: web
    name: ethical-hacking-lms-api
    env: node
    region: oregon
    plan: starter # Changed from free to starter
    buildCommand: cd src/backend && npm install
    startCommand: cd src/backend && node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 30d
      - key: DB_DIALECT
        value: sqlite

  # Frontend static site
  - type: static
    name: ethical-hacking-lms
    buildCommand: cd src/frontend && npm install && npm run build
    publishPath: ./src/frontend/dist # Changed from staticPublishPath to publishPath
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          name: ethical-hacking-lms-api
          type: web
          property: host
        suffix: /api
